filebeat.registry_file: /usr/share/filebeat/data/registry
filebeat.config.prospectors:
#prospectors dynamically loaded from the sub-directory
  path: ${path.config}/prospectors.d/*.yml
  reload.enabled: false
filebeat.modules:
#Filebeat system module consumes logs from host OS through a mounted volume
- module: system
  syslog:
    var.paths: ["/var/log/syslog*"]
#All data to indexed to Elasticsearch
output.elasticsearch:
  hosts: ["elasticsearch:9200"]